name: TestPlugin
version: 1.0
main: gg.skinny.test.TestPlugin
api-version: 1.20
description: Super cool test plugin!
author: iiSkinny
contributors: [ii, Skinny]
website: https://mcworkshop.org
commands:
  heal:
    description: Fully heals the player using the command.
    usage: /heal
  gmc:
    description: Will set you in gamemode creative upon use
    usage: /gmc

  gms:
    description: Will set you in gamemode survival upon use
    usage: /gms

  gmsp:
    description: Will set you in gamemode spectator upon use
    usage: /gmsp
  feed:
    description: Will restore you to full hunger
    usage: /feed
  spawn:
    description: Teleports you to the world's spawn point.
    usage: /spawn
  speed:
    description: Sets your speed (1-10), based on whether you're flying or on the ground.
    usage: /speed <1-10>
