name: TestPlugin
version: 1.0
main: gg.skinny.test.TestPlugin
api-version: 1.20
description: Super cool test plugin!
author: iiSkinny
contributors: [ii, Skinny]
website: https://mcworkshop.org
commands:
  heal:
    description: Fully heals the player using the command.
    usage: /heal

  gmc:
    description: Will set you in gamemode creative upon use
    usage: /gmc

  gms:
    description: Will set you in gamemode survival upon use
    usage: /gms

