# Gets a fresh machine from "git clone" to a running network, and is safe to run again any time.
# Installs Java and Docker if missing, creates network/.env, builds the plugin, and starts everything.

. (Join-Path $PSScriptRoot 'common.ps1')

Write-Step 'Checking Java'
if (-not (Test-Command java)) {
    if (-not (Test-Command winget)) { Fail 'Java is missing. Install a JDK 17 or newer from https://adoptium.net and run this again.' }
    Write-Host 'Java is missing, installing Temurin JDK 21...'
    Invoke-Checked winget @('install', '--exact', '--id', 'EclipseAdoptium.Temurin.21.JDK',
        '--accept-package-agreements', '--accept-source-agreements')
    Update-Path
    if (-not (Test-Command java)) { Fail 'Java was installed. Close this window and run setup again.' }
}
# java prints its version as error output, which must not stop the script.
Write-Done (& { $ErrorActionPreference = 'Continue'; java -version 2>&1 } | Select-Object -First 1 | ForEach-Object { "$_" })

Write-Step 'Checking Docker'
if (-not (Test-Command docker)) {
    if (-not (Test-Command winget)) { Fail 'Docker is missing. Install Docker Desktop from https://docker.com and run this again.' }
    Write-Host 'Docker is missing, installing Docker Desktop...'
    Invoke-Checked winget @('install', '--exact', '--id', 'Docker.DockerDesktop',
        '--accept-package-agreements', '--accept-source-agreements')
    Write-Host ''
    Write-Host 'Docker Desktop was installed. Before running setup again:' -ForegroundColor Yellow
    Write-Host '  1. Open PowerShell as administrator and run:  wsl --install --no-distribution'
    Write-Host '  2. Restart the computer.'
    Write-Host '  3. Open Docker Desktop once and accept its terms.'
    exit 0
}
Wait-Docker
Write-Done (docker version --format 'Docker {{.Server.Version}}')

Write-Step 'Checking network/.env'
$envFile = Join-Path $Network '.env'
if (Test-Path $envFile) {
    Write-Done 'Already exists, keeping it.'
} else {
    # Hex strings, so they never contain characters that need escaping in YAML or the MySQL URL.
    function New-Secret {
        $bytes = New-Object byte[] 24
        [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''
    }
    $lines = @(
        '# Secrets for docker-compose.yml, generated by setup. Never commit this file.',
        "VELOCITY_SECRET=$(New-Secret)",
        "MYSQL_PASSWORD=$(New-Secret)",
        "MYSQL_ROOT_PASSWORD=$(New-Secret)"
    )
    # Without a byte order mark, which Docker Compose would read as part of the first line.
    [IO.File]::WriteAllLines($envFile, $lines)
    Write-Done 'Created with new random passwords.'
}

Write-Step 'Building the plugin'
Push-Location $Root
try { Invoke-Checked (Join-Path $Root 'gradlew.bat') @('deployNetwork', '--console=plain', '--quiet') }
finally { Pop-Location }
Write-Done 'Built network/plugins/SkinnyPlugin.jar'

Write-Step 'Starting the network (the first start downloads a lot and can take a few minutes)'
Push-Location $Network
try { Invoke-Checked docker @('compose', 'up', '-d') }
finally { Pop-Location }

Write-Host ''
Write-Done 'Done! Connect in Minecraft 1.20.1 to:  localhost'
Write-Host 'The servers need a minute or two to finish starting. Watch one with:'
Write-Host '  cd network; docker compose logs -f lobby'
